# Generated by Django 5.2.16 on 2026-07-11 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affectations', '0003_alter_affectationcentre_statut_and_more'),
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('type_kit', models.CharField(choices=[('A_APPORTER', 'À apporter'), ('A_REMETTRE', 'À remettre')], db_index=True, max_length=20)),
                ('quantite', models.PositiveIntegerField(default=1, help_text='Quantité prévue par immergé.')),
                ('unite', models.CharField(default='unité', max_length=50)),
                ('obligatoire', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], db_index=True, default='ACTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('centre', models.ForeignKey(blank=True, help_text='Laisser vide pour un article valable dans tous les centres de la session.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles_kit', to='affectations.centreimmersion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles_kit', to='sessions_app.sessionimmersion')),
            ],
            options={
                'verbose_name': 'Article de kit',
                'verbose_name_plural': 'Articles de kit',
                'db_table': 'articles_kit',
                'ordering': ['session_id', 'centre_id', 'ordre', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='RemiseKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prevue', models.PositiveIntegerField(default=0, help_text='Copie de la quantité prévue au moment de la remise.')),
                ('quantite_remise', models.PositiveIntegerField(default=0)),
                ('statut_remise', models.CharField(choices=[('REMIS', 'Remis'), ('PARTIEL', 'Partiel'), ('NON_REMIS', 'Non remis'), ('REMPLACE', 'Remplacé'), ('DISPENSE', 'Dispensé')], db_index=True, default='NON_REMIS', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('date_remise', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('affectation_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remises_kit', to='affectations.affectationcentre')),
                ('article_kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remises', to='kits.articlekit')),
                ('remis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remises_kit_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remise de kit',
                'verbose_name_plural': 'Remises de kits',
                'db_table': 'remises_kit',
                'ordering': ['-date_remise', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='articlekit',
            index=models.Index(fields=['session', 'type_kit', 'statut'], name='kit_art_sess_type_stat'),
        ),
        migrations.AddIndex(
            model_name='articlekit',
            index=models.Index(fields=['centre', 'type_kit', 'statut'], name='kit_art_ctr_type_stat'),
        ),
        migrations.AddIndex(
            model_name='articlekit',
            index=models.Index(fields=['deleted_at', 'statut'], name='kit_art_del_stat'),
        ),
        migrations.AddConstraint(
            model_name='articlekit',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gte', 1)), name='kit_art_qte_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='articlekit',
            constraint=models.UniqueConstraint(condition=models.Q(('centre__isnull', True), ('deleted_at__isnull', True)), fields=('session', 'designation', 'type_kit'), name='uniq_kit_art_global'),
        ),
        migrations.AddConstraint(
            model_name='articlekit',
            constraint=models.UniqueConstraint(condition=models.Q(('centre__isnull', False), ('deleted_at__isnull', True)), fields=('session', 'centre', 'designation', 'type_kit'), name='uniq_kit_art_centre'),
        ),
        migrations.AddIndex(
            model_name='remisekit',
            index=models.Index(fields=['affectation_centre', 'statut_remise'], name='kit_rem_aff_stat'),
        ),
        migrations.AddIndex(
            model_name='remisekit',
            index=models.Index(fields=['article_kit', 'statut_remise'], name='kit_rem_art_stat'),
        ),
        migrations.AddIndex(
            model_name='remisekit',
            index=models.Index(fields=['date_remise', 'deleted_at'], name='kit_rem_date'),
        ),
        migrations.AddConstraint(
            model_name='remisekit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('affectation_centre', 'article_kit'), name='uniq_remise_kit_active'),
        ),
        migrations.AddConstraint(
            model_name='remisekit',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_prevue__gte', 1)), name='kit_rem_qte_prev_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='remisekit',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_remise__lte', models.F('quantite_prevue'))), name='kit_rem_qte_lte_prev'),
        ),
        migrations.AddConstraint(
            model_name='remisekit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantite_remise', models.F('quantite_prevue')), ('statut_remise', 'REMIS')), models.Q(('quantite_remise__gt', 0), ('quantite_remise__lt', models.F('quantite_prevue')), ('statut_remise', 'PARTIEL')), models.Q(('quantite_remise', 0), ('statut_remise', 'NON_REMIS')), models.Q(('quantite_remise', 0), ('statut_remise', 'DISPENSE')), models.Q(('quantite_remise__gt', 0), ('quantite_remise__lte', models.F('quantite_prevue')), ('statut_remise', 'REMPLACE')), _connector='OR'), name='kit_rem_stat_qte_ok'),
        ),
    ]
