# Generated by Django 5.2.16 on 2026-07-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_corrige_perimetres_affectations_acteurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='perimetre_delegation_max',
            field=models.CharField(blank=True, choices=[('plateforme', 'Plateforme'), ('national', 'National'), ('region', 'Région'), ('centre', 'Centre')], max_length=30),
        ),
    ]
