# Generated by Django 5.2.16 on 2026-07-08 22:48

import django.core.validators
import django.db.models.deletion
import sessions_app.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionImmersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, editable=False, max_length=50, unique=True)),
                ('annee', models.PositiveIntegerField(default=sessions_app.models.annee_courante, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(10000)])),
                ('numero_promotion', models.PositiveIntegerField(default=sessions_app.models.numero_promotion_par_defaut, help_text='Par défaut : 2025 = promotion 1, 2026 = promotion 2, etc.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('type_session', models.CharField(choices=[('examen', 'Examen'), ('concours', 'Concours'), ('selectionne', 'Sélectionné'), ('volontaire', 'Volontaire'), ('mixte', 'Mixte')], max_length=30)),
                ('public_cible', models.CharField(choices=[('BEPC', 'BEPC'), ('BAC', 'BAC'), ('CONCOURS', 'Concours'), ('SELECTIONNE', 'Sélectionné'), ('VOLONTAIRE', 'Volontaire'), ('MIXTE', 'Mixte')], max_length=30)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_ouverture_inscription', models.DateField(blank=True, null=True)),
                ('date_fermeture_inscription', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('ouverte', 'Ouverte'), ('en_preparation', 'En préparation'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('archivee', 'Archivée'), ('annulee', 'Annulée')], db_index=True, default='brouillon', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': "Session d'immersion",
                'verbose_name_plural': "Sessions d'immersion",
                'db_table': 'sessions_immersion',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('annee__gte', 2020), ('annee__lte', 2100)), name='sessions_immersion_annee_2020_2100'), models.CheckConstraint(condition=models.Q(('numero_promotion__gte', 1), ('numero_promotion__lte', 99)), name='sessions_immersion_promotion_1_99')],
            },
        ),
        migrations.CreateModel(
            name='ParametreSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_entree', models.CharField(choices=[('import', 'Import'), ('inscription', 'Inscription'), ('mixte', 'Mixte')], default='import', max_length=30)),
                ('hebergement_active', models.BooleanField(default=True)),
                ('repas_active', models.BooleanField(default=True)),
                ('visite_medicale_active', models.BooleanField(default=False)),
                ('mode_visite_medicale', models.CharField(choices=[('arrivee', "À l'arrivée")], default='arrivee', max_length=30)),
                ('activites_active', models.BooleanField(default=True)),
                ('evaluation_active', models.BooleanField(default=False)),
                ('attestation_active', models.BooleanField(default=True)),
                ('consultation_publique_active', models.BooleanField(default=True)),
                ('taux_presence_minimum_attestation', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('directives_generales', models.TextField(blank=True)),
                ('consignes_generales', models.TextField(blank=True)),
                ('documents_exiges', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='sessions_app.sessionimmersion')),
            ],
            options={
                'verbose_name': 'Paramètre de session',
                'verbose_name_plural': 'Paramètres de session',
                'db_table': 'parametres_session',
                'constraints': [models.CheckConstraint(condition=models.Q(('taux_presence_minimum_attestation__gte', 0), ('taux_presence_minimum_attestation__lte', 100)), name='parametres_session_taux_presence_0_100')],
            },
        ),
    ]
