# Generated by Django 5.2.16 on 2026-07-09 14:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=120, unique=True)),
                ('libelle', models.CharField(max_length=180)),
                ('module', models.CharField(db_index=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('est_systeme', models.BooleanField(default=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'db_table': 'permissions',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('niveau', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('perimetre_autorise', models.CharField(choices=[('plateforme', 'Plateforme'), ('national', 'National'), ('region', 'Région'), ('centre', 'Centre'), ('session', 'Session')], db_index=True, default='national', max_length=30)),
                ('est_systeme', models.BooleanField(default=True)),
                ('est_modifiable', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], db_index=True, default='actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'rôle',
                'verbose_name_plural': 'rôles',
                'db_table': 'roles',
                'ordering': ['niveau', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('titre', models.CharField(blank=True, max_length=150)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='acteurs/signatures/')),
                ('cachet_image', models.ImageField(blank=True, null=True, upload_to='acteurs/cachets/')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('desactive', 'Désactivé')], db_index=True, default='actif', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acteurs_crees', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'acteur',
                'verbose_name_plural': 'acteurs',
                'db_table': 'acteurs',
                'ordering': ['last_name', 'first_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AffectationActeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('niveau_affectation', models.CharField(choices=[('plateforme', 'Plateforme'), ('national', 'National'), ('region', 'Région'), ('centre', 'Centre'), ('session', 'Session')], db_index=True, default='national', max_length=30)),
                ('region_code', models.CharField(blank=True, db_index=True, max_length=30)),
                ('centre_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to=settings.AUTH_USER_MODEL)),
                ('affecte_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "affectation d'acteur",
                'verbose_name_plural': "affectations d'acteurs",
                'db_table': 'affectations_acteurs',
                'ordering': ['-date_debut', 'niveau_affectation', 'region_code', 'centre_id'],
            },
        ),
        migrations.CreateModel(
            name='DemandePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], db_index=True, default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('motif_decision', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_permissions', to=settings.AUTH_USER_MODEL)),
                ('affectation_acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_permissions', to='accounts.affectationacteur')),
                ('decideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_permissions', to='accounts.permission')),
            ],
            options={
                'verbose_name': 'demande de permission',
                'verbose_name_plural': 'demandes de permissions',
                'db_table': 'demandes_permissions',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='AffectationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateField(default=django.utils.timezone.localdate)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('est_delegable', models.BooleanField(default=False)),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('retiree', 'Retirée'), ('expiree', 'Expirée')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('affectation_acteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions_directes', to='accounts.affectationacteur')),
                ('attribue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_attribuees', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_permissions', to='accounts.permission')),
            ],
            options={
                'verbose_name': 'permission directe',
                'verbose_name_plural': 'permissions directes',
                'db_table': 'affectation_permissions',
                'ordering': ['-date_attribution', 'permission__code'],
            },
        ),
        migrations.CreateModel(
            name='DelegationActeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_delegation', models.CharField(choices=[('role', 'Rôle'), ('permission', 'Permission')], db_index=True, max_length=20)),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate)),
                ('date_fin', models.DateField()),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('acteur_cible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations_recues', to=settings.AUTH_USER_MODEL)),
                ('acteur_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations_donnees', to=settings.AUTH_USER_MODEL)),
                ('affectation_acteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations', to='accounts.affectationacteur')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegations', to='accounts.permission')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegations', to='accounts.role')),
            ],
            options={
                'verbose_name': "délégation d'acteur",
                'verbose_name_plural': "délégations d'acteurs",
                'db_table': 'delegations_acteurs',
                'ordering': ['-date_debut', '-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='AffectationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateField(default=django.utils.timezone.localdate)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('retire', 'Retiré'), ('expire', 'Expiré')], db_index=True, default='actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('affectation_acteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles_affectes', to='accounts.affectationacteur')),
                ('attribue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_attribues', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_roles', to='accounts.role')),
            ],
            options={
                'verbose_name': "rôle d'affectation",
                'verbose_name_plural': "rôles d'affectations",
                'db_table': 'affectation_roles',
                'ordering': ['-date_attribution', 'role__niveau'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_delegable', models.BooleanField(default=False)),
                ('perimetre_delegation_max', models.CharField(blank=True, choices=[('plateforme', 'Plateforme'), ('national', 'National'), ('region', 'Région'), ('centre', 'Centre'), ('session', 'Session')], max_length=30)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('retiree', 'Retirée')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles_permission', to='accounts.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions_role', to='accounts.role')),
            ],
            options={
                'verbose_name': 'permission de rôle',
                'verbose_name_plural': 'permissions de rôles',
                'db_table': 'role_permissions',
                'ordering': ['role__niveau', 'role__code', 'permission__module', 'permission__code'],
            },
        ),
    ]
