# Generated by Django 5.2.16 on 2026-07-10 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0001_initial'),
        ('immerges', '0001_initial'),
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='affectationcentre',
            name='unique_affectation_centre_active_par_immerge',
        ),
        migrations.RemoveConstraint(
            model_name='affectationregionale',
            name='unique_affectation_regionale_active_par_immerge',
        ),
        migrations.AlterField(
            model_name='affectationcentre',
            name='statut',
            field=models.CharField(choices=[('PROPOSEE', 'Proposée'), ('ACTIVE', 'Active'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée'), ('TRANSFEREE', 'Transférée')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='affectationregionale',
            name='statut',
            field=models.CharField(choices=[('PROPOSEE', 'Proposée'), ('ACTIVE', 'Active'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée'), ('TRANSFEREE', 'Transférée')], default='ACTIVE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='affectationcentre',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('statut__in', ['PROPOSEE', 'ACTIVE'])), fields=('immerge',), name='unique_affectation_centre_ouverte_par_immerge'),
        ),
        migrations.AddConstraint(
            model_name='affectationregionale',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('statut__in', ['PROPOSEE', 'ACTIVE'])), fields=('immerge',), name='unique_affectation_regionale_ouverte_par_immerge'),
        ),
    ]
