# Generated by Django 5.2.16 on 2026-07-12 20:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affectations', '0003_alter_affectationcentre_statut_and_more'),
        ('immerges', '0001_initial'),
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_evenement', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origine', models.CharField(choices=[('ACTEUR', 'Acteur interne'), ('IMMERGE', 'Immergé'), ('SYSTEME', 'Système'), ('CELERY', 'Tâche Celery'), ('API_PUBLIQUE', 'API publique'), ('ADMIN', 'Administration Django')], db_index=True, max_length=30)),
                ('resultat', models.CharField(choices=[('TENTATIVE', 'Tentative'), ('SUCCES', 'Succès'), ('REFUS', 'Refus'), ('ECHEC', 'Échec'), ('PARTIEL', 'Partiel'), ('ANNULE', 'Annulé')], db_index=True, max_length=20)),
                ('canal', models.CharField(choices=[('API', 'API interne'), ('PORTAIL_PUBLIC', 'Portail public'), ('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('CELERY', 'Celery'), ('ADMIN', 'Administration Django'), ('SYSTEME', 'Système'), ('EXPORT', 'Export')], db_index=True, default='SYSTEME', max_length=30)),
                ('code_action', models.CharField(db_index=True, max_length=140)),
                ('module_source', models.CharField(db_index=True, max_length=80)),
                ('motif', models.TextField(blank=True)),
                ('objet_type', models.CharField(blank=True, db_index=True, max_length=120)),
                ('objet_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('objet_reference', models.CharField(blank=True, max_length=180)),
                ('contexte', models.JSONField(blank=True, default=dict)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('methode_http', models.CharField(blank=True, max_length=12)),
                ('chemin_api', models.CharField(blank=True, max_length=500)),
                ('statut_http', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duree_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journaux_actions', to=settings.AUTH_USER_MODEL)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journaux_actions', to='affectations.centreimmersion')),
                ('immerge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journaux_actions', to='immerges.immerge')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journaux_actions', to='affectations.regionimmersion')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journaux_actions', to='sessions_app.sessionimmersion')),
            ],
            options={
                'verbose_name': "journal d'action",
                'verbose_name_plural': "journaux d'actions",
                'db_table': 'journaux_actions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='journaux_ac_session_59d0f8_idx'), models.Index(fields=['region', 'created_at'], name='journaux_ac_region__7dc9f1_idx'), models.Index(fields=['centre', 'created_at'], name='journaux_ac_centre__b53027_idx'), models.Index(fields=['acteur', 'created_at'], name='journaux_ac_acteur__348981_idx'), models.Index(fields=['immerge', 'created_at'], name='journaux_ac_immerge_2b6b89_idx'), models.Index(fields=['module_source', 'code_action', 'created_at'], name='journaux_ac_module__429889_idx'), models.Index(fields=['origine', 'resultat', 'created_at'], name='journaux_ac_origine_2d0acc_idx'), models.Index(fields=['objet_type', 'objet_id'], name='journaux_ac_objet_t_5f6090_idx')],
            },
        ),
    ]
