# Generated by Django 5.2.16 on 2026-07-11 10:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affectations', '0003_alter_affectationcentre_statut_and_more'),
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiteMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_visite', models.PositiveSmallIntegerField(default=1, help_text='Numéro chronologique de la visite ou contre-visite.')),
                ('est_courante', models.BooleanField(db_index=True, default=True, help_text='Indique la visite actuellement applicable.')),
                ('date_visite', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resultat', models.CharField(blank=True, choices=[('APTE', 'Apte'), ('APTE_SOUS_RESERVE', 'Apte sous réserve'), ('INAPTE_TEMPORAIRE', 'Inapte temporaire'), ('INAPTE_DEFINITIF', 'Inapte définitif'), ('DISPENSE', 'Dispensé')], db_index=True, default='', max_length=30)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], db_index=True, default='BROUILLON', max_length=20)),
                ('observations_medicales', models.TextField(blank=True, help_text='Informations médicales confidentielles. Elles ne doivent jamais être exposées aux modules opérationnels.')),
                ('consignes_operationnelles', models.TextField(blank=True, help_text='Consignes non médicales transmissibles aux responsables et aux modules concernés.')),
                ('document_medical', models.FileField(blank=True, upload_to='sante/documents/%Y/%m/')),
                ('date_prochaine_visite', models.DateField(blank=True, help_text="Date recommandée pour une contre-visite, notamment en cas d'inaptitude temporaire.", null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('statut_application', models.CharField(choices=[('NON_DEMARREE', 'Non démarrée'), ('A_APPLIQUER', 'À appliquer'), ('EN_COURS', 'Application en cours'), ('APPLIQUEE', 'Appliquée'), ('ECHEC', 'Échec')], db_index=True, default='NON_DEMARREE', help_text="État d'application du résultat dans les autres modules FasoIM.", max_length=20)),
                ('date_application', models.DateTimeField(blank=True, null=True)),
                ('erreur_application', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('affectation_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visites_medicales', to='affectations.affectationcentre')),
                ('agent_sante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visites_medicales_saisies', to=settings.AUTH_USER_MODEL)),
                ('centre', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='visites_medicales', to='affectations.centreimmersion')),
                ('session', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='visites_medicales', to='sessions_app.sessionimmersion')),
            ],
            options={
                'verbose_name': 'Visite médicale',
                'verbose_name_plural': 'Visites médicales',
                'db_table': 'visites_medicales',
                'ordering': ['-date_visite', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RestrictionMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=180)),
                ('type_restriction', models.CharField(choices=[('DISPENSE', 'Dispense'), ('ADAPTATION', 'Adaptation'), ('INTERDICTION', 'Interdiction'), ('SURVEILLANCE', 'Surveillance'), ('PRIORITE', 'Priorité'), ('AUTRE', 'Autre')], db_index=True, default='ADAPTATION', max_length=20)),
                ('modules_concernes', models.JSONField(default=list, help_text='Liste des modules qui doivent appliquer la restriction, par exemple HEBERGEMENT, ACTIVITES ou EVALUATIONS.')),
                ('description_medicale', models.TextField(blank=True, help_text='Détail médical confidentiel réservé aux acteurs de santé.')),
                ('consigne_operationnelle', models.TextField(help_text='Consigne non médicale transmise aux modules concernés.')),
                ('niveau_sensibilite', models.CharField(choices=[('OPERATIONNEL', 'Opérationnel'), ('CONFIDENTIEL', 'Confidentiel'), ('STRICTEMENT_CONFIDENTIEL', 'Strictement confidentiel')], default='CONFIDENTIEL', max_length=30)),
                ('date_debut', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('date_fin', models.DateField(blank=True, db_index=True, null=True)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('LEVEE', 'Levée'), ('EXPIREE', 'Expirée'), ('ANNULEE', 'Annulée')], db_index=True, default='ACTIVE', max_length=20)),
                ('date_levee', models.DateTimeField(blank=True, null=True)),
                ('motif_levee', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('saisie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restrictions_medicales_saisies', to=settings.AUTH_USER_MODEL)),
                ('visite_medicale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restrictions', to='sante.visitemedicale')),
            ],
            options={
                'verbose_name': 'Restriction médicale',
                'verbose_name_plural': 'Restrictions médicales',
                'db_table': 'restrictions_medicales',
                'ordering': ['-date_debut', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='visitemedicale',
            index=models.Index(fields=['session', 'centre', 'resultat'], name='sante_vis_sess_ctr_res_idx'),
        ),
        migrations.AddIndex(
            model_name='visitemedicale',
            index=models.Index(fields=['centre', 'statut', 'est_courante'], name='sante_vis_ctr_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='visitemedicale',
            index=models.Index(fields=['statut_application', 'deleted_at'], name='sante_vis_application_idx'),
        ),
        migrations.AddIndex(
            model_name='visitemedicale',
            index=models.Index(fields=['affectation_centre', 'est_courante'], name='sante_vis_aff_cour_idx'),
        ),
        migrations.AddConstraint(
            model_name='visitemedicale',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('est_courante', True)), fields=('affectation_centre',), name='uniq_visite_courante_aff'),
        ),
        migrations.AddConstraint(
            model_name='visitemedicale',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('affectation_centre', 'numero_visite'), name='uniq_numero_visite_aff'),
        ),
        migrations.AddConstraint(
            model_name='visitemedicale',
            constraint=models.CheckConstraint(condition=models.Q(('numero_visite__gte', 1)), name='sante_vis_numero_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='restrictionmedicale',
            index=models.Index(fields=['visite_medicale', 'statut'], name='sante_res_vis_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='restrictionmedicale',
            index=models.Index(fields=['statut', 'date_debut', 'date_fin'], name='sante_res_periode_idx'),
        ),
        migrations.AddIndex(
            model_name='restrictionmedicale',
            index=models.Index(fields=['deleted_at', 'statut'], name='sante_res_del_stat_idx'),
        ),
        migrations.AddConstraint(
            model_name='restrictionmedicale',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='sante_res_dates_ok'),
        ),
    ]
