# Generated by Django 5.2.16 on 2026-07-09 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectationacteur',
            name='session_id',
        ),
        migrations.AddField(
            model_name='affectationacteur',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_acteurs', to='sessions_app.sessionimmersion'),
        ),
    ]
