# Generated for the FasoIM repas module.

import decimal
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sessions_app", "0001_initial"),
        ("affectations", "0003_alter_affectationcentre_statut_and_more"),
        ("organisation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeRavitaillementCentre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("effectif_reference", models.PositiveIntegerField(default=0)),
                ("statut", models.CharField(choices=[("BROUILLON", "Brouillon"), ("SOUMISE", "Soumise"), ("VALIDEE", "Validée"), ("PARTIELLEMENT_RECUE", "Partiellement reçue"), ("RECUE", "Reçue"), ("ANNULEE", "Annulée")], db_index=True, default="BROUILLON", max_length=30)),
                ("observations", models.TextField(blank=True)),
                ("date_soumission", models.DateTimeField(blank=True, null=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("centre", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="demandes_ravitaillement", to="affectations.centreimmersion")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="demandes_ravitaillement", to="sessions_app.sessionimmersion")),
                ("soumis_par", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="demandes_ravitaillement_soumises", to=settings.AUTH_USER_MODEL)),
                ("valide_par", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="demandes_ravitaillement_validees", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Demande de ravitaillement de centre",
                "verbose_name_plural": "Demandes de ravitaillement des centres",
                "db_table": "demandes_ravitaillement_centres",
                "ordering": ["-session__annee", "centre__nom", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LigneBesoinDenree",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_denree", models.CharField(max_length=60)),
                ("designation", models.CharField(max_length=180)),
                ("conditionnement", models.CharField(max_length=80)),
                ("contenance_conditionnement", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("unite_base", models.CharField(max_length=30)),
                ("quantite_demandee", models.DecimalField(decimal_places=3, max_digits=14)),
                ("quantite_validee", models.DecimalField(decimal_places=3, default=decimal.Decimal("0"), max_digits=14)),
                ("quantite_recue", models.DecimalField(decimal_places=3, default=decimal.Decimal("0"), max_digits=14)),
                ("observations", models.TextField(blank=True)),
                ("statut", models.CharField(choices=[("BROUILLON", "Brouillon"), ("VALIDEE", "Validée"), ("PARTIELLEMENT_RECUE", "Partiellement reçue"), ("RECUE", "Reçue"), ("ANNULEE", "Annulée")], db_index=True, default="BROUILLON", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("demande_ravitaillement", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lignes_denrees", to="repas.demanderavitaillementcentre")),
            ],
            options={
                "verbose_name": "Ligne de besoin en denrée",
                "verbose_name_plural": "Lignes de besoins en denrées",
                "db_table": "lignes_besoins_denrees",
                "ordering": ["designation", "id"],
            },
        ),
        migrations.CreateModel(
            name="RepasJournalier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_repas", models.DateField(db_index=True)),
                ("type_repas", models.CharField(choices=[("PETIT_DEJEUNER", "Petit déjeuner"), ("DEJEUNER", "Déjeuner"), ("DINER", "Dîner"), ("COLLATION", "Collation")], db_index=True, max_length=25)),
                ("heure_prevue", models.TimeField(blank=True, null=True)),
                ("menu_prevu", models.CharField(max_length=255)),
                ("description_prevue", models.TextField(blank=True)),
                ("denrees_prevues", models.JSONField(blank=True, default=list)),
                ("nombre_standard_prevu", models.PositiveIntegerField(default=0)),
                ("synthese_restrictions_alimentaires", models.JSONField(blank=True, default=dict, editable=False)),
                ("preparations_speciales_prevues", models.JSONField(blank=True, default=dict)),
                ("menu_prepare", models.CharField(blank=True, max_length=255)),
                ("description_preparation_reelle", models.TextField(blank=True)),
                ("denrees_reellement_utilisees", models.JSONField(blank=True, default=list)),
                ("nombre_standard_prepare", models.PositiveIntegerField(default=0)),
                ("preparations_speciales_reelles", models.JSONField(blank=True, default=dict)),
                ("heure_debut_preparation", models.DateTimeField(blank=True, null=True)),
                ("heure_fin_preparation", models.DateTimeField(blank=True, null=True)),
                ("observations_preparation", models.TextField(blank=True)),
                ("statut_controle_sante", models.CharField(choices=[("NON_VERIFIE", "Non vérifié"), ("A_JOUR", "À jour"), ("A_REVOIR", "À revoir")], db_index=True, default="NON_VERIFIE", max_length=20)),
                ("date_verification_sante", models.DateTimeField(blank=True, null=True)),
                ("empreinte_besoins_sante", models.CharField(blank=True, editable=False, max_length=64)),
                ("statut", models.CharField(choices=[("BROUILLON", "Brouillon"), ("PLANIFIE", "Planifié"), ("VALIDE", "Validé"), ("EN_PREPARATION", "En préparation"), ("PREPARE", "Préparé"), ("DISTRIBUTION_OUVERTE", "Distribution ouverte"), ("CLOTURE", "Clôturé"), ("ANNULE", "Annulé")], db_index=True, default="BROUILLON", max_length=30)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("date_ouverture_distribution", models.DateTimeField(blank=True, null=True)),
                ("date_cloture", models.DateTimeField(blank=True, null=True)),
                ("motif_annulation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("cree_par", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="repas_journaliers_crees", to=settings.AUTH_USER_MODEL)),
                ("demande_ravitaillement", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="repas_journaliers", to="repas.demanderavitaillementcentre")),
                ("valide_par", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="repas_journaliers_valides", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Repas journalier",
                "verbose_name_plural": "Repas journaliers",
                "db_table": "repas_journaliers",
                "ordering": ["-date_repas", "type_repas", "id"],
            },
        ),
        migrations.CreateModel(
            name="SuiviRepas",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type_suivi", models.CharField(choices=[("COMPTAGE", "Comptage"), ("MEDICAL", "Suivi alimentaire")], db_index=True, max_length=15)),
                ("effectif_attendu", models.PositiveIntegerField(default=0)),
                ("nombre_ayant_mange", models.PositiveIntegerField(default=0)),
                ("categorie_alimentaire", models.CharField(blank=True, max_length=255)),
                ("consigne_alimentaire", models.TextField(blank=True)),
                ("preparation_speciale_prevue", models.TextField(blank=True)),
                ("statut_service", models.CharField(blank=True, choices=[("A_SERVIR", "À servir"), ("SERVI_CONFORME", "Servi conformément"), ("SERVI_NON_CONFORME", "Servi non conformément"), ("NON_SERVI", "Non servi"), ("ABSENT", "Absent"), ("REFUSE", "Refusé")], db_index=True, default="", max_length=25)),
                ("observation_service", models.TextField(blank=True)),
                ("observations", models.TextField(blank=True)),
                ("date_saisie", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("affectation_centre", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="suivis_repas_medicaux", to="affectations.affectationcentre")),
                ("groupe", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="suivis_repas", to="organisation.groupe")),
                ("repas_journalier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="suivis", to="repas.repasjournalier")),
                ("saisi_par", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="suivis_repas_saisis", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Suivi de repas",
                "verbose_name_plural": "Suivis de repas",
                "db_table": "suivis_repas",
                "ordering": ["repas_journalier_id", "type_suivi", "id"],
            },
        ),
        migrations.AddIndex(model_name="demanderavitaillementcentre", index=models.Index(fields=["session", "centre", "statut"], name="rep_dem_sess_ctr_stat")),
        migrations.AddIndex(model_name="demanderavitaillementcentre", index=models.Index(fields=["deleted_at", "statut"], name="rep_dem_del_stat")),
        migrations.AddConstraint(model_name="demanderavitaillementcentre", constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("session", "centre"), name="uniq_dem_ravit_sess_ctr_active")),
        migrations.AddIndex(model_name="lignebesoindenree", index=models.Index(fields=["demande_ravitaillement", "statut"], name="rep_lig_dem_stat")),
        migrations.AddIndex(model_name="lignebesoindenree", index=models.Index(fields=["code_denree"], name="rep_lig_code")),
        migrations.AddConstraint(model_name="lignebesoindenree", constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("demande_ravitaillement", "code_denree"), name="uniq_lig_denree_dem_code_active")),
        migrations.AddConstraint(model_name="lignebesoindenree", constraint=models.CheckConstraint(condition=models.Q(("quantite_demandee__gt", 0)), name="rep_lig_qte_dem_gt_zero")),
        migrations.AddConstraint(model_name="lignebesoindenree", constraint=models.CheckConstraint(condition=models.Q(("quantite_validee__gte", 0)), name="rep_lig_qte_val_pos")),
        migrations.AddConstraint(model_name="lignebesoindenree", constraint=models.CheckConstraint(condition=models.Q(("quantite_recue__gte", 0)), name="rep_lig_qte_rec_pos")),
        migrations.AddIndex(model_name="repasjournalier", index=models.Index(fields=["date_repas", "type_repas", "statut"], name="rep_repas_date_type_stat")),
        migrations.AddIndex(model_name="repasjournalier", index=models.Index(fields=["demande_ravitaillement", "statut"], name="rep_repas_dem_stat")),
        migrations.AddIndex(model_name="repasjournalier", index=models.Index(fields=["statut_controle_sante", "date_repas"], name="rep_repas_sante_date")),
        migrations.AddConstraint(model_name="repasjournalier", constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("demande_ravitaillement", "date_repas", "type_repas"), name="uniq_repas_dem_date_type_active")),
        migrations.AddIndex(model_name="suivirepas", index=models.Index(fields=["repas_journalier", "type_suivi"], name="rep_suivi_repas_type")),
        migrations.AddIndex(model_name="suivirepas", index=models.Index(fields=["statut_service", "deleted_at"], name="rep_suivi_serv_del")),
        migrations.AddConstraint(model_name="suivirepas", constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("groupe__isnull", False), ("type_suivi", "COMPTAGE")), fields=("repas_journalier", "groupe"), name="uniq_suivi_comptage_repas_groupe")),
        migrations.AddConstraint(model_name="suivirepas", constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("groupe__isnull", True), ("type_suivi", "COMPTAGE")), fields=("repas_journalier",), name="uniq_suivi_comptage_repas_centre")),
        migrations.AddConstraint(model_name="suivirepas", constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("type_suivi", "MEDICAL")), fields=("repas_journalier", "affectation_centre"), name="uniq_suivi_med_repas_aff")),
        migrations.AddConstraint(model_name="suivirepas", constraint=models.CheckConstraint(condition=models.Q(("nombre_ayant_mange__lte", models.F("effectif_attendu"))), name="rep_suivi_mange_lte_attendu")),
    ]
