# Generated by Django 5.2.16 on 2026-07-11 07:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affectations', '0003_alter_affectationcentre_statut_and_more'),
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('capacite_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('DESACTIVE', 'Désactivé'), ('ARCHIVE', 'Archivé')], db_index=True, default='ACTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['section__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Dortoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('capacite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sexe_dortoir', models.CharField(choices=[('MASCULIN', 'Masculin'), ('FEMININ', 'Féminin')], max_length=20)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('HORS_SERVICE', 'Hors service'), ('ARCHIVE', 'Archivé')], db_index=True, default='ACTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dortoirs', to='affectations.centreimmersion')),
            ],
            options={
                'verbose_name': 'Dortoir',
                'verbose_name_plural': 'Dortoirs',
                'ordering': ['centre__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='AffectationGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PROPOSEE', 'Proposée'), ('ACTIVE', 'Active'), ('A_REORGANISER', 'À réorganiser'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée'), ('TRANSFEREE', 'Transférée')], db_index=True, default='PROPOSEE', max_length=25)),
                ('date_affectation', models.DateTimeField(default=django.utils.timezone.now)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('affectation_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_groupes', to='affectations.affectationcentre')),
                ('affecte_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_groupes_effectuees', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='organisation.groupe')),
            ],
            options={
                'verbose_name': 'Affectation à un groupe',
                'verbose_name_plural': 'Affectations aux groupes',
                'ordering': ['-date_affectation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lit', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('HORS_SERVICE', 'Hors service'), ('ARCHIVE', 'Archivé')], db_index=True, default='DISPONIBLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dortoir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lits', to='organisation.dortoir')),
            ],
            options={
                'verbose_name': 'Lit',
                'verbose_name_plural': 'Lits',
                'ordering': ['dortoir__nom', 'numero_lit'],
            },
        ),
        migrations.CreateModel(
            name='AttributionLit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PROPOSEE', 'Proposée'), ('ACTIVE', 'Active'), ('A_REORGANISER', 'À réorganiser'), ('REJETEE', 'Rejetée'), ('LIBEREE', 'Libérée'), ('ANNULEE', 'Annulée'), ('TRANSFEREE', 'Transférée')], db_index=True, default='PROPOSEE', max_length=25)),
                ('date_attribution', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_liberation', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('affectation_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributions_lits', to='affectations.affectationcentre')),
                ('attribue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions_lits_effectuees', to=settings.AUTH_USER_MODEL)),
                ('lit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='organisation.lit')),
            ],
            options={
                'verbose_name': 'Attribution de lit',
                'verbose_name_plural': 'Attributions de lits',
                'ordering': ['-date_attribution', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RegleOrganisationCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_division_sections', models.PositiveIntegerField(help_text='À partir de cet effectif total, le système peut proposer plusieurs sections. En dessous, il crée une seule section.', validators=[django.core.validators.MinValueValidator(2)])),
                ('capacite_max_section', models.PositiveIntegerField(help_text='Capacité maximale autorisée pour une section.', validators=[django.core.validators.MinValueValidator(1)])),
                ('seuil_division_groupes', models.PositiveIntegerField(help_text='À partir de cet effectif dans une section, le système peut proposer plusieurs groupes. En dessous, il crée un seul groupe.', validators=[django.core.validators.MinValueValidator(2)])),
                ('capacite_max_groupe', models.PositiveIntegerField(help_text='Capacité maximale autorisée pour un groupe.', validators=[django.core.validators.MinValueValidator(1)])),
                ('repartition_sections_groupes_automatique', models.BooleanField(default=True, help_text='Autorise le système à proposer automatiquement les sections, groupes et affectations internes.')),
                ('attribution_lits_automatique', models.BooleanField(default=True, help_text="Autorise le système à proposer automatiquement les dortoirs et lits lorsque l'hébergement est activé dans la session.")),
                ('lieu_accueil', models.CharField(blank=True, max_length=255)),
                ('heure_accueil', models.TimeField(blank=True, null=True)),
                ('horaires_generaux', models.TextField(blank=True)),
                ('consignes_accueil', models.TextField(blank=True)),
                ('consignes_hebergement', models.TextField(blank=True)),
                ('consignes_kits_a_apporter', models.TextField(blank=True)),
                ('consignes_repas', models.TextField(blank=True)),
                ('regles_discipline', models.TextField(blank=True)),
                ('consignes_internes', models.TextField(blank=True)),
                ('directives_locales', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'Organisation en cours'), ('VALIDEE', 'Organisation validée'), ('PRETE_PUBLICATION', 'Prête pour publication'), ('ARCHIVEE', 'Archivée')], db_index=True, default='BROUILLON', max_length=30)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_pret_publication', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regles_organisation', to='affectations.centreimmersion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regles_organisation_centres', to='sessions_app.sessionimmersion')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regles_organisation_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Règle d'organisation de centre",
                'verbose_name_plural': "Règles d'organisation des centres",
                'ordering': ['-session__annee', 'centre__nom', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('capacite_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('DESACTIVEE', 'Désactivée'), ('ARCHIVEE', 'Archivée')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='affectations.centreimmersion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='sessions_app.sessionimmersion')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['session', 'centre__nom', 'code'],
            },
        ),
        migrations.AddField(
            model_name='groupe',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupes', to='organisation.section'),
        ),
        migrations.AddIndex(
            model_name='dortoir',
            index=models.Index(fields=['centre', 'sexe_dortoir', 'statut'], name='organisatio_centre__da8836_idx'),
        ),
        migrations.AddIndex(
            model_name='dortoir',
            index=models.Index(fields=['deleted_at'], name='organisatio_deleted_756148_idx'),
        ),
        migrations.AddConstraint(
            model_name='dortoir',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('centre', 'nom'), name='uniq_dortoir_centre_nom_active'),
        ),
        migrations.AddIndex(
            model_name='affectationgroupe',
            index=models.Index(fields=['affectation_centre', 'statut'], name='organisatio_affecta_45c945_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationgroupe',
            index=models.Index(fields=['groupe', 'statut'], name='organisatio_groupe__6e77bb_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationgroupe',
            index=models.Index(fields=['deleted_at'], name='organisatio_deleted_a6cf14_idx'),
        ),
        migrations.AddConstraint(
            model_name='affectationgroupe',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('statut__in', ['PROPOSEE', 'ACTIVE', 'A_REORGANISER'])), fields=('affectation_centre',), name='uniq_affectation_groupe_ouverte_centre'),
        ),
        migrations.AddIndex(
            model_name='lit',
            index=models.Index(fields=['dortoir', 'statut'], name='organisatio_dortoir_94a69f_idx'),
        ),
        migrations.AddIndex(
            model_name='lit',
            index=models.Index(fields=['numero_lit'], name='organisatio_numero__6c4e50_idx'),
        ),
        migrations.AddIndex(
            model_name='lit',
            index=models.Index(fields=['deleted_at'], name='organisatio_deleted_7927e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='lit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('dortoir', 'numero_lit'), name='uniq_lit_dortoir_numero_active'),
        ),
        migrations.AddIndex(
            model_name='attributionlit',
            index=models.Index(fields=['affectation_centre', 'statut'], name='organisatio_affecta_9fd339_idx'),
        ),
        migrations.AddIndex(
            model_name='attributionlit',
            index=models.Index(fields=['lit', 'statut'], name='organisatio_lit_id_4c2662_idx'),
        ),
        migrations.AddIndex(
            model_name='attributionlit',
            index=models.Index(fields=['deleted_at'], name='organisatio_deleted_a1d9cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='attributionlit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('statut__in', ['PROPOSEE', 'ACTIVE', 'A_REORGANISER'])), fields=('affectation_centre',), name='uniq_attribution_lit_ouverte_centre'),
        ),
        migrations.AddConstraint(
            model_name='attributionlit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('statut__in', ['PROPOSEE', 'ACTIVE', 'A_REORGANISER'])), fields=('lit',), name='uniq_attribution_lit_ouverte_lit'),
        ),
        migrations.AddIndex(
            model_name='regleorganisationcentre',
            index=models.Index(fields=['session', 'centre', 'statut'], name='organisatio_session_9ffbe7_idx'),
        ),
        migrations.AddIndex(
            model_name='regleorganisationcentre',
            index=models.Index(fields=['centre', 'statut'], name='organisatio_centre__6c26db_idx'),
        ),
        migrations.AddIndex(
            model_name='regleorganisationcentre',
            index=models.Index(fields=['deleted_at'], name='organisatio_deleted_1bb740_idx'),
        ),
        migrations.AddConstraint(
            model_name='regleorganisationcentre',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('session', 'centre'), name='uniq_regle_org_session_centre_active'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['session', 'centre', 'statut'], name='organisatio_session_4f6e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['code'], name='organisatio_code_a58c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['deleted_at'], name='organisatio_deleted_586d89_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('session', 'centre', 'code'), name='uniq_section_session_centre_code_active'),
        ),
        migrations.AddIndex(
            model_name='groupe',
            index=models.Index(fields=['section', 'statut'], name='organisatio_section_9b01e7_idx'),
        ),
        migrations.AddIndex(
            model_name='groupe',
            index=models.Index(fields=['code'], name='organisatio_code_3659ea_idx'),
        ),
        migrations.AddIndex(
            model_name='groupe',
            index=models.Index(fields=['deleted_at'], name='organisatio_deleted_135ebf_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupe',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('section', 'code'), name='uniq_groupe_section_code_active'),
        ),
    ]
