# Generated by Django 5.2.16 on 2026-07-15 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regleorganisationcentre',
            name='capacite_ouverte',
            field=models.PositiveIntegerField(default=1, help_text='Nombre maximal de places mises à disposition par le centre pour cette session.', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
