# Generated by Django 5.2.16 on 2026-07-10 07:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportOfficiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_source', models.CharField(choices=[('BEPC', 'BEPC'), ('BAC', 'BAC'), ('CONCOURS', 'Concours'), ('SELECTIONNES', 'Sélectionnés'), ('VOLONTAIRES_ACCEPTES', 'Volontaires acceptés')], db_index=True, max_length=40)),
                ('type_fichier', models.CharField(choices=[('EXCEL', 'Excel'), ('CSV', 'CSV')], default='EXCEL', max_length=20)),
                ('fichier', models.FileField(max_length=500, upload_to='imports/officiels/%Y/%m/')),
                ('nom_fichier_original', models.CharField(max_length=255)),
                ('taille_fichier', models.PositiveBigIntegerField(default=0)),
                ('hash_fichier', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('statut', models.CharField(choices=[('RECU', 'Reçu'), ('LECTURE_COLONNES_EN_COURS', 'Lecture des colonnes en cours'), ('CORRESPONDANCE_REQUISE', 'Correspondance requise'), ('CORRESPONDANCE_VALIDEE', 'Correspondance validée'), ('VALIDATION_EN_COURS', 'Validation en cours'), ('VALIDE', 'Valide'), ('VALIDE_AVEC_ERREURS', 'Valide avec erreurs'), ('CONFIRMATION_EN_COURS', 'Confirmation en cours'), ('TERMINE', 'Terminé'), ('ECHEC', 'Échec'), ('ANNULE', 'Annulé')], db_index=True, default='RECU', max_length=40)),
                ('colonnes_detectees', models.JSONField(blank=True, default=list)),
                ('apercu_lignes', models.JSONField(blank=True, default=list)),
                ('message_erreur', models.TextField(blank=True, default='')),
                ('commentaire', models.TextField(blank=True, default='')),
                ('total_lignes', models.PositiveIntegerField(default=0)),
                ('lignes_valides', models.PositiveIntegerField(default=0)),
                ('lignes_erreur', models.PositiveIntegerField(default=0)),
                ('lignes_ignorees', models.PositiveIntegerField(default=0)),
                ('lignes_importees', models.PositiveIntegerField(default=0)),
                ('date_import', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_lecture_colonnes', models.DateTimeField(blank=True, null=True)),
                ('date_correspondance', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('date_fin_traitement', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('confirme_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_confirmes', to=settings.AUTH_USER_MODEL)),
                ('correspondance_confirmee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_correspondances_confirmees', to=settings.AUTH_USER_MODEL)),
                ('importe_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_officiels_crees', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports_officiels', to='sessions_app.sessionimmersion')),
            ],
            options={
                'verbose_name': 'Import officiel',
                'verbose_name_plural': 'Imports officiels',
                'ordering': ['-date_import', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CorrespondanceColonneImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_cible', models.CharField(db_index=True, max_length=120)),
                ('libelle_champ_cible', models.CharField(blank=True, default='', max_length=180)),
                ('colonne_source', models.CharField(max_length=255)),
                ('obligatoire', models.BooleanField(default=False)),
                ('confirmee', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('transformation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('import_officiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondances', to='imports_app.importofficiel')),
            ],
            options={
                'verbose_name': 'Correspondance de colonne',
                'verbose_name_plural': 'Correspondances de colonnes',
                'ordering': ['ordre', 'champ_cible'],
            },
        ),
        migrations.CreateModel(
            name='LigneImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ligne', models.PositiveIntegerField()),
                ('donnees_brutes', models.JSONField(blank=True, default=dict)),
                ('donnees_normalisees', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Valide'), ('ERREUR', 'Erreur'), ('IGNOREE', 'Ignorée'), ('IMPORTEE', 'Importée')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('message_statut', models.TextField(blank=True, default='')),
                ('hash_ligne', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('import_officiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='imports_app.importofficiel')),
            ],
            options={
                'verbose_name': "Ligne d'import",
                'verbose_name_plural': "Lignes d'import",
                'ordering': ['import_officiel', 'numero_ligne'],
            },
        ),
        migrations.CreateModel(
            name='ErreurImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_cible', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('colonne_source', models.CharField(blank=True, default='', max_length=255)),
                ('type_erreur', models.CharField(choices=[('CHAMP_OBLIGATOIRE', 'Champ obligatoire'), ('FORMAT_INVALIDE', 'Format invalide'), ('VALEUR_INVALIDE', 'Valeur invalide'), ('DOUBLON_FICHIER', 'Doublon dans le fichier'), ('DOUBLON_BASE', 'Doublon dans la base'), ('INCOHERENCE', 'Incohérence'), ('SYSTEME', 'Erreur système')], db_index=True, max_length=40)),
                ('gravite', models.CharField(choices=[('BLOQUANTE', 'Bloquante'), ('AVERTISSEMENT', 'Avertissement')], db_index=True, default='BLOQUANTE', max_length=20)),
                ('message', models.TextField()),
                ('valeur_recue', models.TextField(blank=True, default='')),
                ('code_erreur', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('import_officiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erreurs', to='imports_app.importofficiel')),
                ('ligne_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erreurs', to='imports_app.ligneimport')),
            ],
            options={
                'verbose_name': "Erreur d'import",
                'verbose_name_plural': "Erreurs d'import",
                'ordering': ['ligne_import__numero_ligne', 'champ_cible', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='importofficiel',
            index=models.Index(fields=['session', 'type_source', 'statut'], name='imports_app_session_1112c9_idx'),
        ),
        migrations.AddIndex(
            model_name='importofficiel',
            index=models.Index(fields=['statut', 'date_import'], name='imports_app_statut_15545f_idx'),
        ),
        migrations.AddIndex(
            model_name='importofficiel',
            index=models.Index(fields=['deleted_at', 'statut'], name='imports_app_deleted_e32ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondancecolonneimport',
            index=models.Index(fields=['import_officiel', 'champ_cible'], name='imports_app_import__c0eb91_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondancecolonneimport',
            index=models.Index(fields=['import_officiel', 'colonne_source'], name='imports_app_import__e8ca84_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondancecolonneimport',
            index=models.Index(fields=['deleted_at', 'confirmee'], name='imports_app_deleted_acac40_idx'),
        ),
        migrations.AddConstraint(
            model_name='correspondancecolonneimport',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('import_officiel', 'champ_cible'), name='uniq_correspondance_import_champ_actif'),
        ),
        migrations.AddConstraint(
            model_name='correspondancecolonneimport',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('import_officiel', 'colonne_source'), name='uniq_correspondance_import_colonne_active'),
        ),
        migrations.AddIndex(
            model_name='ligneimport',
            index=models.Index(fields=['import_officiel', 'statut'], name='imports_app_import__2fabb8_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneimport',
            index=models.Index(fields=['import_officiel', 'numero_ligne'], name='imports_app_import__d26842_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneimport',
            index=models.Index(fields=['deleted_at', 'statut'], name='imports_app_deleted_9b676e_idx'),
        ),
        migrations.AddConstraint(
            model_name='ligneimport',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('import_officiel', 'numero_ligne'), name='uniq_ligne_import_numero_actif'),
        ),
        migrations.AddIndex(
            model_name='erreurimport',
            index=models.Index(fields=['import_officiel', 'gravite'], name='imports_app_import__0da0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='erreurimport',
            index=models.Index(fields=['import_officiel', 'type_erreur'], name='imports_app_import__7259b6_idx'),
        ),
        migrations.AddIndex(
            model_name='erreurimport',
            index=models.Index(fields=['ligne_import', 'gravite'], name='imports_app_ligne_i_ff8e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='erreurimport',
            index=models.Index(fields=['deleted_at', 'gravite'], name='imports_app_deleted_3c38d3_idx'),
        ),
    ]
