# Generated by Django 5.2.16 on 2026-07-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importofficiel',
            name='parametres_lecture',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
