# Generated by Django 5.2.16 on 2026-07-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0002_remove_affectationcentre_unique_affectation_centre_active_par_immerge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationcentre',
            name='statut',
            field=models.CharField(choices=[('PROPOSEE', 'Proposée'), ('ACTIVE', 'Active'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée'), ('TRANSFEREE', 'Transférée')], default='PROPOSEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='affectationregionale',
            name='statut',
            field=models.CharField(choices=[('PROPOSEE', 'Proposée'), ('ACTIVE', 'Active'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée'), ('TRANSFEREE', 'Transférée')], default='PROPOSEE', max_length=20),
        ),
    ]
