# Generated by Django 5.2.16 on 2026-07-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0003_alter_affectationcentre_statut_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='centreimmersion',
            name='centre_immersion_capacite_positive',
        ),
        migrations.RemoveField(
            model_name='centreimmersion',
            name='capacite_totale',
        ),
    ]
