# Generated by Django 5.2.16 on 2026-07-12 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affectations', '0003_alter_affectationcentre_statut_and_more'),
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ALERTE', 'Alerte'), ('INCIDENT', 'Incident')], db_index=True, default='ALERTE', max_length=20)),
                ('origine', models.CharField(choices=[('AUTOMATIQUE', 'Automatique'), ('MANUELLE', 'Manuelle'), ('SYSTEME_SECURITE', 'Système / sécurité')], db_index=True, default='MANUELLE', max_length=30)),
                ('type_concerne', models.CharField(choices=[('IMMERGE', 'Immergé'), ('ACTEUR', 'Acteur interne'), ('CENTRE', 'Centre'), ('SESSION', 'Session'), ('DONNEE', 'Donnée métier'), ('SYSTEME', 'Système')], db_index=True, default='DONNEE', max_length=20)),
                ('categorie', models.CharField(choices=[('SECURITE_ACCES', 'Sécurité et accès'), ('AFFECTATION', 'Affectation'), ('ORGANISATION', 'Organisation'), ('IMPORT', 'Import'), ('SANTE', 'Santé / accident'), ('DISCIPLINE', 'Discipline'), ('LOGISTIQUE', 'Logistique'), ('KIT', 'Kit'), ('ACTIVITE', 'Activité / présence'), ('REPAS', 'Repas'), ('SESSION', 'Session'), ('SYSTEME', 'Système'), ('AUTRE', 'Autre')], db_index=True, default='AUTRE', max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('niveau_gravite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], db_index=True, default='MOYEN', max_length=20)),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente'), ('RESOLU', 'Résolu'), ('CLOTURE', 'Clôturé'), ('ANNULE', 'Annulé')], db_index=True, default='NOUVEAU', max_length=20)),
                ('code_detection', models.CharField(blank=True, db_index=True, max_length=100)),
                ('module_source', models.CharField(blank=True, db_index=True, max_length=80)),
                ('modele_source', models.CharField(blank=True, max_length=100)),
                ('objet_source_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('cle_deduplication', models.CharField(blank=True, db_index=True, max_length=255)),
                ('contexte', models.JSONField(blank=True, default=dict)),
                ('est_bloquante', models.BooleanField(db_index=True, default=False)),
                ('resolution_automatique', models.BooleanField(default=False)),
                ('nombre_occurrences', models.PositiveIntegerField(default=1)),
                ('niveau_escalade', models.PositiveSmallIntegerField(default=0)),
                ('date_premiere_detection', models.DateTimeField(blank=True, null=True)),
                ('date_derniere_detection', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_derniere_escalade', models.DateTimeField(blank=True, null=True)),
                ('date_signalement', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('date_prise_en_charge', models.DateTimeField(blank=True, null=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('acteur_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_le_concernant', to=settings.AUTH_USER_MODEL)),
                ('affectation_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertes_incidents', to='affectations.affectationcentre')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertes_incidents', to='affectations.centreimmersion')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_signales', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertes_incidents', to='sessions_app.sessionimmersion')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alerte ou incident',
                'verbose_name_plural': 'alertes et incidents',
                'db_table': 'alertes_incidents',
                'ordering': ['-date_signalement', '-id'],
                'indexes': [models.Index(fields=['session', 'centre', 'statut'], name='inc_ses_ctr_stat_idx'), models.Index(fields=['categorie', 'niveau_gravite', 'statut'], name='inc_cat_grav_stat_idx'), models.Index(fields=['origine', 'module_source', 'statut'], name='inc_org_mod_stat_idx'), models.Index(fields=['cree_par', 'date_signalement'], name='inc_createur_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('cle_deduplication', ''), _negated=True), ('statut__in', ['NOUVEAU', 'EN_COURS', 'EN_ATTENTE'])), fields=('cle_deduplication',), name='uniq_incident_auto_ouvert_cle'), models.CheckConstraint(condition=models.Q(('nombre_occurrences__gte', 1)), name='incident_occurrences_positives')],
            },
        ),
    ]
