# Generated by Django 5.2.16 on 2026-07-10 19:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('immerges', '0001_initial'),
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionImmersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code stable de la région, par exemple CENTRE ou HAUTS_BASSINS.', max_length=50, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('DESACTIVEE', 'Désactivée')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Région d'immersion",
                'verbose_name_plural': "Régions d'immersion",
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['code'], name='affectation_code_bfd010_idx'), models.Index(fields=['statut', 'deleted_at'], name='affectation_statut_b6af8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CentreImmersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique du centre, par exemple CENTRE-001.', max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=150)),
                ('adresse', models.TextField(blank=True)),
                ('capacite_totale', models.PositiveIntegerField(default=0)),
                ('genre', models.CharField(choices=[('MASCULIN', 'Masculin'), ('FEMININ', 'Féminin'), ('MIXTE', 'Mixte')], default='MIXTE', max_length=20)),
                ('publics_acceptes', models.JSONField(blank=True, default=list, help_text='Liste des publics acceptés : BEPC, BAC, CONCOURS, SELECTIONNE, VOLONTAIRE.')),
                ('niveaux_acceptes', models.JSONField(blank=True, default=list, help_text='Liste des niveaux ou séries acceptés : BEPC, BAC, BAC_D, BAC_A, etc.')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('MAINTENANCE', 'Maintenance'), ('DESACTIVE', 'Désactivé'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centres', to='affectations.regionimmersion')),
            ],
            options={
                'verbose_name': "Centre d'immersion",
                'verbose_name_plural': "Centres d'immersion",
                'ordering': ['region__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='AffectationRegionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée'), ('TRANSFEREE', 'Transférée')], default='ACTIVE', max_length=20)),
                ('date_affectation', models.DateTimeField(default=django.utils.timezone.now)),
                ('motif', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('affecte_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_regionales_effectuees', to=settings.AUTH_USER_MODEL)),
                ('immerge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_regionales', to='immerges.immerge')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_regionales', to='sessions_app.sessionimmersion')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_regionales', to='affectations.regionimmersion')),
            ],
            options={
                'verbose_name': 'Affectation régionale',
                'verbose_name_plural': 'Affectations régionales',
                'ordering': ['-date_affectation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AffectationCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée'), ('TRANSFEREE', 'Transférée')], default='ACTIVE', max_length=20)),
                ('date_affectation', models.DateTimeField(default=django.utils.timezone.now)),
                ('motif', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('affecte_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_centres_effectuees', to=settings.AUTH_USER_MODEL)),
                ('immerge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_centres', to='immerges.immerge')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_centres', to='sessions_app.sessionimmersion')),
                ('affectation_regionale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_centres', to='affectations.affectationregionale')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_centres', to='affectations.centreimmersion')),
            ],
            options={
                'verbose_name': 'Affectation centre',
                'verbose_name_plural': 'Affectations centres',
                'ordering': ['-date_affectation', '-id'],
                'indexes': [models.Index(fields=['session', 'centre', 'statut'], name='affectation_session_5a1e7c_idx'), models.Index(fields=['immerge', 'statut'], name='affectation_immerge_d359e5_idx'), models.Index(fields=['deleted_at'], name='affectation_deleted_6a8b0c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('statut', 'ACTIVE')), fields=('immerge',), name='unique_affectation_centre_active_par_immerge')],
            },
        ),
        migrations.AddIndex(
            model_name='centreimmersion',
            index=models.Index(fields=['code'], name='affectation_code_f224f9_idx'),
        ),
        migrations.AddIndex(
            model_name='centreimmersion',
            index=models.Index(fields=['region', 'statut'], name='affectation_region__03010a_idx'),
        ),
        migrations.AddIndex(
            model_name='centreimmersion',
            index=models.Index(fields=['deleted_at'], name='affectation_deleted_10e2a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='centreimmersion',
            constraint=models.CheckConstraint(condition=models.Q(('capacite_totale__gte', 0)), name='centre_immersion_capacite_positive'),
        ),
        migrations.AddIndex(
            model_name='affectationregionale',
            index=models.Index(fields=['session', 'region', 'statut'], name='affectation_session_39c27a_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationregionale',
            index=models.Index(fields=['immerge', 'statut'], name='affectation_immerge_96b7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationregionale',
            index=models.Index(fields=['deleted_at'], name='affectation_deleted_9cab6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='affectationregionale',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('statut', 'ACTIVE')), fields=('immerge',), name='unique_affectation_regionale_active_par_immerge'),
        ),
    ]
