# Generated by Django 5.2.16 on 2026-07-14 12:37

import django.core.validators
import sessions_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_parametresession_moyenne_minimum_attestation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessionimmersion',
            name='sessions_immersion_annee_2020_2100',
        ),
        migrations.AddField(
            model_name='sessionimmersion',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionimmersion',
            name='motif_annulation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sessionimmersion',
            name='annee',
            field=models.PositiveIntegerField(default=sessions_app.models.annee_courante, validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='sessionimmersion',
            name='numero_promotion',
            field=models.PositiveIntegerField(default=sessions_app.models.numero_promotion_par_defaut, help_text='Par défaut : 2025 = promotion 1, 2026 = promotion 2, etc.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddConstraint(
            model_name='sessionimmersion',
            constraint=models.CheckConstraint(condition=models.Q(('annee__gte', 2025), ('annee__lte', 2100)), name='sessions_immersion_annee_2025_2100'),
        ),
    ]
