# Generated by Django 5.2.16 on 2026-07-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0003_remove_sessionimmersion_sessions_immersion_annee_2020_2100_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionimmersion',
            name='cloture_proposee_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionimmersion',
            name='cloture_proposee_blocages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
