# Generated by Django 5.2.16 on 2026-07-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0004_sessionimmersion_cloture_proposee_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresession',
            name='centres_accueil',
            field=models.JSONField(blank=True, default=list, help_text='Photographie des centres retenus pour la session : centre_id, centre_code et centre_nom.'),
        ),
    ]
