# Generated by Django 5.2.16 on 2026-07-11 15:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affectations', '0003_alter_affectationcentre_statut_and_more'),
        ('organisation', '0001_initial'),
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=60)),
                ('categorie', models.CharField(choices=[('FORMATION', 'Formation'), ('SPORT', 'Sport'), ('SENSIBILISATION', 'Sensibilisation'), ('ORIENTATION', 'Orientation'), ('DISCIPLINE', 'Discipline'), ('CULTURE', 'Culture'), ('AUTRE', 'Autre')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('obligatoire', models.BooleanField(default=True, help_text='Valeur par défaut utilisée lors de la planification dans une session.')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], db_index=True, default='ACTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': "Module d'activité",
                'verbose_name_plural': "Modules d'activité",
                'db_table': 'modules_activite',
                'ordering': ['categorie', 'titre', 'id'],
                'indexes': [models.Index(fields=['categorie', 'statut'], name='act_mod_cat_stat'), models.Index(fields=['deleted_at', 'statut'], name='act_mod_del_stat')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='uniq_module_activite_code_actif'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('titre', 'categorie'), name='uniq_module_activite_titre_cat')],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField(db_index=True)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('lieu', models.CharField(max_length=180)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], db_index=True, default='BROUILLON', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances_activite', to='affectations.centreimmersion')),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seances_animees', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seances_activite', to='organisation.groupe')),
                ('module_activite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='activites.moduleactivite')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seances_activite', to='organisation.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances_activite', to='sessions_app.sessionimmersion')),
            ],
            options={
                'verbose_name': "Séance d'activité",
                'verbose_name_plural': "Séances d'activité",
                'db_table': 'seances_activite',
                'ordering': ['date_seance', 'heure_debut', 'centre_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_presence', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'Retard'), ('EXCUSE', 'Excusé'), ('DISPENSE', 'Dispensé')], db_index=True, max_length=20)),
                ('heure_pointage', models.TimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('affectation_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences_activite', to='affectations.affectationcentre')),
                ('saisie_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences_activite_saisies', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='activites.seance')),
            ],
            options={
                'verbose_name': 'Présence à une activité',
                'verbose_name_plural': 'Présences aux activités',
                'db_table': 'presences_activite',
                'ordering': ['seance_id', 'affectation_centre_id'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=180)),
                ('type_evaluation', models.CharField(choices=[('QUIZ', 'Quiz'), ('TEST', 'Test'), ('PRATIQUE', 'Pratique'), ('PARTICIPATION', 'Participation'), ('COMPORTEMENT', 'Comportement'), ('AUTRE', 'Autre')], db_index=True, max_length=30)),
                ('bareme', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_evaluation', models.DateTimeField(db_index=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('OUVERTE', 'Ouverte'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée')], db_index=True, default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_activite', to='affectations.centreimmersion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_activite', to='sessions_app.sessionimmersion')),
                ('module_activite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='activites.moduleactivite')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='activites.seance')),
            ],
            options={
                'verbose_name': "Évaluation d'activité",
                'verbose_name_plural': "Évaluations d'activités",
                'db_table': 'evaluations_activite',
                'ordering': ['date_evaluation', 'centre_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('statut', models.CharField(choices=[('SAISIE', 'Saisie'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée'), ('DISPENSE', 'Dispensée')], db_index=True, default='SAISIE', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('affectation_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes_activite', to='affectations.affectationcentre')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='activites.evaluation')),
                ('saisie_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes_activite_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Note d'activité",
                'verbose_name_plural': "Notes d'activités",
                'db_table': 'notes_activite',
                'ordering': ['evaluation_id', 'affectation_centre_id'],
                'indexes': [models.Index(fields=['evaluation', 'statut'], name='act_note_eval_stat'), models.Index(fields=['affectation_centre', 'statut'], name='act_note_aff_stat')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('evaluation', 'affectation_centre'), name='uniq_note_active_eval_immerge'), models.CheckConstraint(condition=models.Q(models.Q(('statut', 'DISPENSE'), ('valeur__isnull', True)), ('statut', 'ANNULEE'), models.Q(('statut__in', ['SAISIE', 'VALIDEE']), ('valeur__gte', 0), ('valeur__isnull', False)), _connector='OR'), name='act_note_statut_valeur_ok')],
            },
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['session', 'centre', 'date_seance', 'statut'], name='act_sea_sess_ctr_date'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['formateur', 'date_seance'], name='act_sea_form_date'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['groupe', 'date_seance'], name='act_sea_grp_date'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['section', 'date_seance'], name='act_sea_sec_date'),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.CheckConstraint(condition=models.Q(('heure_fin__gt', models.F('heure_debut'))), name='act_seance_heure_fin_apres_debut'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['seance', 'statut_presence'], name='act_pre_sea_stat'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['affectation_centre', 'statut_presence'], name='act_pre_aff_stat'),
        ),
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('seance', 'affectation_centre'), name='uniq_presence_active_seance_immerge'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['session', 'centre', 'date_evaluation', 'statut'], name='act_eval_sess_ctr_dt'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['module_activite', 'statut'], name='act_eval_mod_stat'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(condition=models.Q(('bareme__gt', 0)), name='act_eval_bareme_gt_zero'),
        ),
    ]
