# Generated by Django 5.2.16 on 2026-07-11 16:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0001_initial'),
        ('affectations', '0003_alter_affectationcentre_statut_and_more'),
        ('organisation', '0001_initial'),
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleactivite',
            options={'ordering': ['ordre', 'categorie', 'titre', 'id'], 'verbose_name': "Module d'activité", 'verbose_name_plural': "Modules d'activité"},
        ),
        migrations.RemoveConstraint(
            model_name='note',
            name='act_note_statut_valeur_ok',
        ),
        migrations.RemoveIndex(
            model_name='evaluation',
            name='act_eval_mod_stat',
        ),
        migrations.RemoveIndex(
            model_name='note',
            name='act_note_eval_stat',
        ),
        migrations.RemoveIndex(
            model_name='note',
            name='act_note_aff_stat',
        ),
        migrations.RenameField(
            model_name='presence',
            old_name='heure_pointage',
            new_name='heure_arrivee',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='module_activite',
        ),
        migrations.RemoveField(
            model_name='moduleactivite',
            name='obligatoire',
        ),
        migrations.RemoveField(
            model_name='note',
            name='statut',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_activite_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduleactivite',
            name='duree_prevue',
            field=models.PositiveIntegerField(blank=True, help_text="Durée indicative de l'activité en minutes.", null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='moduleactivite',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='appreciation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='date_saisie',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='note',
            name='statut_note',
            field=models.CharField(choices=[('NOTEE', 'Notée'), ('ABSENT', 'Absent'), ('DISPENSE', 'Dispensée'), ('ANNULEE', 'Annulée')], db_index=True, default='NOTEE', max_length=20),
        ),
        migrations.AddField(
            model_name='presence',
            name='date_saisie',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='seance',
            name='date_cloture_presence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seance',
            name='date_ouverture_presence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seance',
            name='date_validation_presence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seance',
            name='presences_validees_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feuilles_presence_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seance',
            name='statut_feuille_presence',
            field=models.CharField(choices=[('NON_OUVERTE', 'Non ouverte'), ('OUVERTE', 'Ouverte'), ('VALIDEE', 'Validée'), ('CLOTUREE', 'Clôturée')], db_index=True, default='NON_OUVERTE', max_length=20),
        ),
        migrations.AddField(
            model_name='seance',
            name='titre',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='type_evaluation',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('TEST', 'Test'), ('PRATIQUE', 'Pratique'), ('COMPORTEMENT', 'Comportement'), ('PARTICIPATION', 'Participation'), ('FINALE', 'Finale'), ('AUTRE', 'Autre')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='moduleactivite',
            name='categorie',
            field=models.CharField(choices=[('FORMATION', 'Formation'), ('SENSIBILISATION', 'Sensibilisation'), ('SPORT', 'Sport'), ('CIVISME', 'Civisme'), ('DISCIPLINE', 'Discipline'), ('ORIENTATION', 'Orientation'), ('CULTURE', 'Culture'), ('AUTRE', 'Autre')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='seance',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('REPORTEE', 'Reportée'), ('ANNULEE', 'Annulée')], db_index=True, default='BROUILLON', max_length=20),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['type_evaluation', 'statut'], name='act_eval_type_stat'),
        ),
        migrations.AddIndex(
            model_name='moduleactivite',
            index=models.Index(fields=['ordre', 'statut'], name='act_mod_ordre_stat'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['evaluation', 'statut_note'], name='act_note_eval_stat'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['affectation_centre', 'statut_note'], name='act_note_aff_stat'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['date_saisie'], name='act_note_date_saisie'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['date_saisie'], name='act_pre_date_saisie'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['statut_feuille_presence', 'date_seance'], name='act_sea_feuille_date'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(condition=models.Q(('coefficient__gt', 0)), name='act_eval_coef_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('statut_note', 'NOTEE'), ('valeur__gte', 0), ('valeur__isnull', False)), models.Q(('statut_note__in', ['ABSENT', 'DISPENSE']), ('valeur__isnull', True)), ('statut_note', 'ANNULEE'), _connector='OR'), name='act_note_statut_valeur_ok'),
        ),
    ]
