# Generated by Django 5.2.16 on 2026-07-12 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def renseigner_region_et_confidentialite(apps, schema_editor):
    AlerteIncident = apps.get_model("incidents", "AlerteIncident")
    CentreImmersion = apps.get_model("affectations", "CentreImmersion")
    AffectationCentre = apps.get_model("affectations", "AffectationCentre")

    regions_centres = dict(
        CentreImmersion.objects.values_list("id", "region_id")
    )
    regions_affectations = dict(
        AffectationCentre.objects.values_list("id", "centre__region_id")
    )

    a_modifier = []
    for incident in AlerteIncident.objects.all().iterator(chunk_size=500):
        if incident.centre_id:
            incident.region_id = regions_centres.get(incident.centre_id)
        elif incident.affectation_centre_id:
            incident.region_id = regions_affectations.get(incident.affectation_centre_id)

        if incident.categorie == "SANTE":
            incident.niveau_confidentialite = "MEDICALE"
        elif incident.origine == "MANUELLE":
            incident.niveau_confidentialite = "RESTREINTE"
        else:
            incident.niveau_confidentialite = "NORMALE"
        a_modifier.append(incident)
        if len(a_modifier) >= 500:
            AlerteIncident.objects.bulk_update(
                a_modifier,
                ["region", "niveau_confidentialite"],
                batch_size=500,
            )
            a_modifier.clear()
    if a_modifier:
        AlerteIncident.objects.bulk_update(
            a_modifier,
            ["region", "niveau_confidentialite"],
            batch_size=500,
        )


def migration_inverse(apps, schema_editor):
    # Les deux colonnes sont supprimées par une éventuelle migration inverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0003_alter_affectationcentre_statut_and_more'),
        ('incidents', '0001_initial'),
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerteincident',
            name='niveau_confidentialite',
            field=models.CharField(choices=[('NORMALE', 'Normale'), ('RESTREINTE', 'Restreinte'), ('MEDICALE', 'Médicale')], db_index=True, default='NORMALE', max_length=20),
        ),
        migrations.AddField(
            model_name='alerteincident',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertes_incidents', to='affectations.regionimmersion'),
        ),
        migrations.RunPython(
            renseigner_region_et_confidentialite,
            migration_inverse,
        ),
        migrations.AddIndex(
            model_name='alerteincident',
            index=models.Index(fields=['session', 'region', 'statut'], name='inc_ses_reg_stat_idx'),
        ),
    ]
